/* eslint-disable max-depth */
import { getYtdlpSettings } from "@spotify-to-plex/plex-config/functions/getYtdlpSettings";
import { getStorageDir } from "@spotify-to-plex/shared-utils/utils/getStorageDir";
import { SlskdTrackData } from "@spotify-to-plex/shared-types/slskd/SlskdTrackData";
import { YtdlpClient } from "@spotify-to-plex/shared-utils/ytdlp/client";
import { waitForDownloadComplete } from "@spotify-to-plex/shared-utils/ytdlp/waitForDownloadComplete";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { getNestedSyncLogsForType } from "../utils/getNestedSyncLogsForType";
import { startSyncType } from "../utils/startSyncType";
import { clearSyncTypeLogs } from "../utils/clearSyncTypeLogs";
import { completeSyncType } from "../utils/completeSyncType";
import { errorSyncType } from "../utils/errorSyncType";
import { updateSyncTypeProgress } from "../utils/updateSyncTypeProgress";

export async function syncYtdlp() {
    console.log("=".repeat(60));
    console.log("Starting YT-DLP sync...");
    console.log("=".repeat(60));

    // Check yt-dlp settings
    const settings = await getYtdlpSettings();
    console.log(`YT-DLP Settings: enabled=${settings.enabled}, fallback_only=${settings.fallback_only}`);

    if (!settings.enabled) {
        console.log("❌ YT-DLP sync is disabled");
        return;
    }

    // Start sync type logging
    startSyncType("ytdlp");
    clearSyncTypeLogs("ytdlp");

    try {
        // Validate configuration
        if (!settings.api_url) {
            console.error("❌ YT-DLP API URL not configured");
            throw new Error("yt-dlp API URL not configured");
        }

        if (!settings.api_key) {
            console.error("❌ YT-DLP API key not configured");
            throw new Error("yt-dlp API key not configured");
        }

        console.log(`✓ API URL: ${settings.api_url}`);

        // Initialize client
        const client = new YtdlpClient(settings.api_url, settings.api_key);

        // Test connection
        console.log("🔌 Testing connection to yt-dlp-host...");
        const health = await client.health();
        console.log(`✓ Connected to yt-dlp-host: ${health.version}`);

        // Read missing tracks from YT-DLP JSON file (generated by playlists/albums sync)
        const tracksPath = join(getStorageDir(), "missing_tracks_ytdlp.json");
        if (!existsSync(tracksPath)) {
            console.log("⚠️  No missing tracks file found at:", tracksPath);
            completeSyncType("ytdlp");
            return;
        }

        const content = readFileSync(tracksPath, "utf8");
        let tracks: SlskdTrackData[] = [];

        try {
            tracks = JSON.parse(content);
        } catch (_e) {
            console.error("❌ Failed to parse missing tracks JSON");
            throw new Error("Failed to parse missing tracks JSON");
        }

        if (tracks.length === 0) {
            console.log("ℹ️  No missing tracks to process");
            completeSyncType("ytdlp");
            return;
        }

        console.log(`📋 Found ${tracks.length} tracks to process`);

        if (settings.fallback_only) {
            console.log(`🔄 Fallback mode: Processing tracks not found by SLSKD`);
        } else {
            console.log(`🔄 Full mode: Processing all missing tracks`);
        }

        // Initialize logs
        const { putLog, logComplete, logError } = getNestedSyncLogsForType("ytdlp");
        const syncLog = putLog("ytdlp-sync", "YT-DLP Sync");

        // Read existing YT-DLP logs
        const ytdlpLogsPath = join(getStorageDir(), 'ytdlp_sync_log.json');
        const ytdlpLogs: Record<string, any> = {};

        let successCount = 0;
        let failureCount = 0;

        // Process tracks (filtering already done during file generation)
        for (let i = 0; i < tracks.length; i++) {
            const track = tracks[i];
            if (!track) continue;

            const trackKey = `${track.artist_name}||${track.track_name}`;

            const trackLog = putLog(
                `${track.artist_name} - ${track.track_name}`,
                `${track.artist_name} - ${track.track_name}`
            );

            const logId = `${Date.now()}-${trackKey}`;
            const detailedLog: any = {
                id: logId,
                artist_name: track.artist_name,
                track_name: track.track_name,
                start: Date.now(),
                status: 'error',
            };

            try {
                // Attempt download with retries
                let downloadSuccess = false;

                for (let retryAttempt = 0; retryAttempt <= settings.retry_limit; retryAttempt++) {
                    try {
                        if (retryAttempt > 0) {
                            console.log(
                                `[${track.artist_name} - ${track.track_name}] Retry attempt ${retryAttempt}/${settings.retry_limit}`
                            );
                        }

                        // Search for the video
                        const searchQuery = `${track.artist_name} - ${track.track_name}`;
                        console.log(`[${track.artist_name} - ${track.track_name}] Searching YouTube...`);

                        const searchResp = await client.search(searchQuery);

                        if (!searchResp.success || !searchResp.url) {
                            throw new Error(searchResp.message || "No video found on YouTube");
                        }

                        console.log(`[${track.artist_name} - ${track.track_name}] Found video: ${searchResp.title}`);

                        // Initiate download with the found video URL
                        const downloadResp = await client.download({
                            url: searchResp.url,
                            audio_format: settings.audio_format,
                            output_format: settings.audio_container,
                            output_filename: `${track.artist_name} - ${track.track_name}`, // Filename without extension
                        });

                        if (!downloadResp.task_id) {
                            throw new Error("No task ID returned from download request");
                        }

                        // Wait for completion
                        console.log(
                            `[${track.artist_name} - ${track.track_name}] Waiting for download...`
                        );
                        const statusResp = await waitForDownloadComplete(client, downloadResp.task_id, {
                            pollInterval: settings.poll_interval,
                            maxAttempts: settings.poll_max_attempts,
                        });

                        // Check if download was successful
                        if (statusResp.status === "error") {
                            throw new Error(statusResp.error || "Download failed");
                        }

                        if (statusResp.status === "completed" && statusResp.file) {
                            console.log(
                                `[${track.artist_name} - ${track.track_name}] ✓ Downloaded successfully`
                            );
                            detailedLog.status = 'completed';
                            detailedLog.video_url = searchResp.url;
                            detailedLog.video_title = searchResp.title;
                            detailedLog.file_path = statusResp.file;
                            downloadSuccess = true;
                            successCount++;
                            break; // Exit retry loop on success
                        } else {
                            throw new Error(`Unexpected status: ${statusResp.status}`);
                        }
                    } catch (retryError) {
                        const errorMsg =
                            retryError instanceof Error ? retryError.message : String(retryError);

                        if (retryAttempt === settings.retry_limit) {
                            throw retryError;
                        }

                        console.log(
                            `[${track.artist_name} - ${track.track_name}] Attempt failed: ${errorMsg}`
                        );

                        // Wait before retry
                        await new Promise((resolve) => setTimeout(resolve, 2000));
                    }
                }

                if (!downloadSuccess) {
                    throw new Error("All download attempts exhausted");
                }

                detailedLog.end = Date.now();
                ytdlpLogs[logId] = detailedLog;
                logComplete(trackLog);
            } catch (error) {
                const errorMsg = error instanceof Error ? error.message : String(error);
                detailedLog.status = 'error';
                detailedLog.error = errorMsg;
                detailedLog.end = Date.now();
                failureCount++;
                ytdlpLogs[logId] = detailedLog;

                console.log(
                    `[${track.artist_name} - ${track.track_name}] ✗ Failed: ${errorMsg}`
                );
                logError(trackLog, errorMsg);
            }

            // Update progress
            updateSyncTypeProgress("ytdlp", i + 1, tracks.length);
        }

        console.log("=".repeat(60));
        console.log(`✅ YT-DLP sync complete:`);
        console.log(`   • ${successCount} succeeded`);
        console.log(`   • ${failureCount} failed`);
        console.log("=".repeat(60));

        // Save YT-DLP logs
        writeFileSync(ytdlpLogsPath, JSON.stringify(ytdlpLogs, null, 2));
        console.log(`📄 Detailed logs saved to ytdlp_sync_log.json`);

        logComplete(syncLog);
        completeSyncType("ytdlp");
    } catch (error) {
        const errorMsg = error instanceof Error ? error.message : String(error);
        console.error("=".repeat(60));
        console.error("❌ YT-DLP sync error:", errorMsg);
        console.error("=".repeat(60));
        errorSyncType("ytdlp", errorMsg);
        throw error;
    }
}

function run() {
    syncYtdlp()
        .then(() => {
            console.log('YT-DLP sync completed');
        })
        .catch((e: unknown) => {
            console.error('YT-DLP sync failed:', e);
        });
}

// Only run if this file is executed directly, not when imported
// eslint-disable-next-line unicorn/prefer-module
if (require.main === module) {
    run();
}
